### ISSUE TITLE
getting PermissionError: [WinError 5] Access is denied: 'Stability' when running SD in nuke

### ISSUE THREAD

**Issue by brintonian** [besarismaili/Stable-Diffusion-for-NUKE#3]
Hello! Wondering if you know what would cause this error. I've added python to Windows PATH during installation. 

Traceback (most recent call last):
  File "<string>", line 16, in <module>
  File "C:\Program Files\Nuke13.2v2\lib\os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "C:\Program Files\Nuke13.2v2\lib\os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [WinError 5] Access is denied: 'Stability'

Any advice would be greatly appreciated!

**Comment by akoeste3dpu** [comment]
Is your script saved? I got this error when I was trying to use it in an unsaved script. It needs to grab the path to the script in order to create subdirectories for the images it generates.

**Comment by brintonian** [comment]
> Is your script saved? I got this error when I was trying to use it in an unsaved script. It needs to grab the path to the script in order to create subdirectories for the images it generates.

That was it! Thank you so much. It's working perfectly now.
